### ISSUE TITLE
Unify blog theme with rest of website

### ISSUE THREAD

**Issue by LiamlShaw** [The-NOVA-System/old#2]

**Comment by garv-shah** [comment]
https://github.com/The-NOVA-System/blog/commit/8243c91edd1aa9eb44d4c440f29f0776a402f6d6

**Comment by garv-shah** [comment]
https://github.com/The-NOVA-System/the-nova-system.github.io/commit/dddca130a26aef5a6f9c9027ad80164d1c61d8e5
